name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    env:
      CC: ${{matrix.compiler}}
    strategy:
      matrix:
        compiler: [clang, gcc]
        BUILD_TYPE: [Release, Debug]
        TOYWASM_USE_SEPARATE_EXECUTE: [ON, OFF]
        TOYWASM_USE_TAILCALL: [ON, OFF]
        TOYWASM_ENABLE_TRACING: [ON, OFF]
        exclude:
          - TOYWASM_USE_SEPARATE_EXECUTE: OFF
            TOYWASM_USE_TAILCALL: ON

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wabt libcmocka-dev clang lld llvm-dev

    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} \
          -DTOYWASM_USE_SEPARATE_EXECUTE=${{matrix.TOYWASM_USE_SEPARATE_EXECUTE}} \
          -DTOYWASM_USE_TAILCALL=${{matrix.TOYWASM_USE_TAILCALL}} \
          -DTOYWASM_ENABLE_TRACING=${{matrix.TOYWASM_ENABLE_TRACING}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{matrix.BUILD_TYPE}} -V
